export interface Alternative {
  id: string
  name: string
  category: string
  replaces: string[]
  description: string
  website: string
  difficulty: 'facile' | 'moyen' | 'avancé'
  impact: 'faible' | 'moyen' | 'élevé'
  freeLevel: 'gratuit' | 'freemium' | 'open-source'
  features: string[]
  educationReady: boolean
  rgpdCompliant: boolean
  image?: string
}

export const ALTERNATIVES: Alternative[] = [
  // Système d'exploitation
  {
    id: 'ubuntu',
    name: 'Ubuntu',
    category: 'Système d\'exploitation',
    replaces: ['Windows 10', 'Windows 11'],
    description: 'Distribution Linux populaire, idéale pour débuter. Interface intuitive proche de Windows/macOS.',
    website: 'https://ubuntu.com/download',
    difficulty: 'facile',
    impact: 'élevé',
    freeLevel: 'open-source',
    features: ['Installation simple', 'Grande communauté francophone', 'Support LTS 5 ans', 'Compatible ancien matériel'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'linux-mint',
    name: 'Linux Mint',
    category: 'Système d\'exploitation',
    replaces: ['Windows 10', 'Windows 11'],
    description: 'Basé sur Ubuntu, avec une interface très proche de Windows. Parfait pour la transition.',
    website: 'https://linuxmint.com/',
    difficulty: 'facile',
    impact: 'élevé',
    freeLevel: 'open-source',
    features: ['Interface Windows-like', 'Codecs multimédia inclus', 'Très stable', 'Faible consommation'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'debian-edu',
    name: 'Debian Edu / Skolelinux',
    category: 'Système d\'exploitation',
    replaces: ['Windows Server', 'Windows 10'],
    description: 'Distribution conçue spécifiquement pour les écoles. Inclut serveur et postes clients.',
    website: 'https://blends.debian.org/edu/',
    difficulty: 'avancé',
    impact: 'élevé',
    freeLevel: 'open-source',
    features: ['Solution complète école', 'Gestion centralisée', 'Profils utilisateurs', 'Filtrage web intégré'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Suite bureautique
  {
    id: 'libreoffice',
    name: 'LibreOffice',
    category: 'Suite bureautique',
    replaces: ['Microsoft Office', 'Microsoft 365'],
    description: 'Suite bureautique complète et gratuite. Compatible avec les formats Microsoft.',
    website: 'https://fr.libreoffice.org/',
    difficulty: 'facile',
    impact: 'élevé',
    freeLevel: 'open-source',
    features: ['Writer, Calc, Impress, Draw', 'Formats ODF et Microsoft', 'Disponible en français', 'Multiplateforme'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'onlyoffice',
    name: 'OnlyOffice',
    category: 'Suite bureautique',
    replaces: ['Microsoft Office', 'Google Docs'],
    description: 'Suite bureautique moderne avec excellente compatibilité Microsoft. Version web disponible.',
    website: 'https://www.onlyoffice.com/fr/',
    difficulty: 'facile',
    impact: 'élevé',
    freeLevel: 'open-source',
    features: ['Interface moderne', 'Édition collaborative', 'Compatible MS Office', 'Intégration Nextcloud'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Cloud et stockage
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    category: 'Cloud / Stockage',
    replaces: ['Google Drive', 'OneDrive', 'Dropbox'],
    description: 'Plateforme cloud complète auto-hébergée. Stockage, calendrier, contacts, visio...',
    website: 'https://nextcloud.com/',
    difficulty: 'moyen',
    impact: 'élevé',
    freeLevel: 'open-source',
    features: ['Stockage illimité', 'Apps intégrées', 'Sync mobile', 'Contrôle total des données'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'apps-education',
    name: 'Apps.education.fr',
    category: 'Cloud / Stockage',
    replaces: ['Google Workspace', 'Microsoft 365'],
    description: 'Suite d\'outils du Ministère de l\'Éducation. Nextcloud, visio, pads, tout inclus !',
    website: 'https://apps.education.fr/',
    difficulty: 'facile',
    impact: 'élevé',
    freeLevel: 'gratuit',
    features: ['Hébergé par l\'État', '100% RGPD', 'Formation disponible', 'Support académique'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Visioconférence
  {
    id: 'bigbluebutton',
    name: 'BigBlueButton',
    category: 'Visioconférence',
    replaces: ['Zoom', 'Google Meet', 'Teams'],
    description: 'Solution de visioconférence conçue pour l\'éducation. Tableau blanc, sondages, sous-groupes.',
    website: 'https://bigbluebutton.org/',
    difficulty: 'moyen',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Tableau blanc interactif', 'Enregistrement', 'Sous-groupes', 'Intégration Moodle'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'jitsi',
    name: 'Jitsi Meet',
    category: 'Visioconférence',
    replaces: ['Zoom', 'Google Meet'],
    description: 'Visioconférence simple, sans compte requis. Instances françaises disponibles.',
    website: 'https://meet.jit.si/',
    difficulty: 'facile',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Sans inscription', 'Chiffrement', 'Partage d\'écran', 'Chat intégré'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Navigateur
  {
    id: 'firefox',
    name: 'Mozilla Firefox',
    category: 'Navigateur',
    replaces: ['Google Chrome', 'Microsoft Edge'],
    description: 'Navigateur libre respectueux de la vie privée. Développé par une fondation non-profit.',
    website: 'https://www.mozilla.org/fr/firefox/',
    difficulty: 'facile',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Protection pistage', 'Conteneurs', 'Sync sécurisé', 'Extensions libres'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Messagerie
  {
    id: 'thunderbird',
    name: 'Thunderbird',
    category: 'Messagerie',
    replaces: ['Outlook', 'Gmail'],
    description: 'Client mail complet par Mozilla. Calendrier et contacts intégrés.',
    website: 'https://www.thunderbird.net/fr/',
    difficulty: 'facile',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Multi-comptes', 'Calendrier', 'Contacts', 'Chiffrement'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // LMS
  {
    id: 'moodle',
    name: 'Moodle',
    category: 'Plateforme pédagogique',
    replaces: ['Google Classroom', 'Microsoft Teams Education'],
    description: 'LMS le plus utilisé au monde. Cours en ligne, quiz, devoirs, forum.',
    website: 'https://moodle.org/?lang=fr',
    difficulty: 'moyen',
    impact: 'élevé',
    freeLevel: 'open-source',
    features: ['Cours structurés', 'Quiz avancés', 'Badges', 'Plugins nombreux'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Création
  {
    id: 'gimp',
    name: 'GIMP',
    category: 'Création graphique',
    replaces: ['Photoshop'],
    description: 'Éditeur d\'images professionnel gratuit. Alternative complète à Photoshop.',
    website: 'https://www.gimp.org/',
    difficulty: 'moyen',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Retouche photo', 'Calques', 'Filtres', 'Scripts'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'inkscape',
    name: 'Inkscape',
    category: 'Création graphique',
    replaces: ['Illustrator'],
    description: 'Éditeur de graphiques vectoriels. Idéal pour logos, affiches, schémas.',
    website: 'https://inkscape.org/fr/',
    difficulty: 'moyen',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Vectoriel SVG', 'Outils dessin', 'Texte avancé', 'Extensions'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'kdenlive',
    name: 'Kdenlive',
    category: 'Montage vidéo',
    replaces: ['Premiere Pro', 'Final Cut'],
    description: 'Éditeur vidéo professionnel libre. Multi-piste, effets, transitions.',
    website: 'https://kdenlive.org/',
    difficulty: 'moyen',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Multi-piste', 'Effets', 'Titrage', 'Export HD'],
    educationReady: true,
    rgpdCompliant: true,
  },
  {
    id: 'audacity',
    name: 'Audacity',
    category: 'Audio',
    replaces: ['Adobe Audition'],
    description: 'Éditeur audio gratuit et simple. Parfait pour podcasts et projets scolaires.',
    website: 'https://www.audacityteam.org/',
    difficulty: 'facile',
    impact: 'faible',
    freeLevel: 'open-source',
    features: ['Enregistrement', 'Multi-piste', 'Effets', 'Export MP3'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Programmation
  {
    id: 'vscodium',
    name: 'VSCodium',
    category: 'Programmation',
    replaces: ['Visual Studio Code'],
    description: 'VS Code sans la télémétrie Microsoft. Même fonctionnalités, plus de vie privée.',
    website: 'https://vscodium.com/',
    difficulty: 'facile',
    impact: 'faible',
    freeLevel: 'open-source',
    features: ['Identique à VS Code', 'Sans télémétrie', 'Extensions', 'Git intégré'],
    educationReady: true,
    rgpdCompliant: true,
  },
  // Communication
  {
    id: 'element',
    name: 'Element (Matrix)',
    category: 'Messagerie instantanée',
    replaces: ['Slack', 'Discord', 'WhatsApp'],
    description: 'Messagerie décentralisée et chiffrée. Idéale pour la communication d\'équipe.',
    website: 'https://element.io/',
    difficulty: 'facile',
    impact: 'moyen',
    freeLevel: 'open-source',
    features: ['Chiffrement E2E', 'Salons', 'Appels vidéo', 'Ponts vers autres apps'],
    educationReady: true,
    rgpdCompliant: true,
  },
]

export const CATEGORIES = [
  'Système d\'exploitation',
  'Suite bureautique', 
  'Cloud / Stockage',
  'Visioconférence',
  'Navigateur',
  'Messagerie',
  'Plateforme pédagogique',
  'Création graphique',
  'Montage vidéo',
  'Audio',
  'Programmation',
  'Messagerie instantanée',
]
